config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show] 
  end

  resources :posts, only: [:new, :create, :destroy] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :comments, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :index]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    if user.admin?
      can :manage, :all
    else
      can %i[read create], :all
      can %i[update destroy], Post, user: user
      can :destroy, Comment, user: user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_comments_counter(value)
    post.update(comments_counter: value)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_likes_counter(value)
    post.update(likes_counter: value)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true,
                    length: { maximum: 250, too_long: 'must not exceed 250 characters' }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter(value)
    user.update('posts_counter', value)
  end

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: self
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  # validates :name, presence: { message: 'Name must not be blank' }
  validates_numericality_of :posts_counter, only_integer: true, greater_than_or_equal: 0

  def admin?
    role == 'admin'
  end

  def recent_posts(limit = 3)
    posts.includes(:comments).order(created_at: :desc).limit(limit)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @comments = Comment.where({ post_id: params[:post_id] }).order('created_at')
    render json: { success: true, data: { comments: @comments } }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], user: current_user)

    if @comment.save
      render json: { success: true, data: { comment: @comment } }, status: :created
    else
      render json: { success: false, errors: @comment.errors }, status: :bad_request
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all.order('created_at')
    render json: { success: true, data: { posts: @posts } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    post = Post.find(params[:post_id])
    new_comment = Comment.create(user_id: current_user.id, post_id: post.id, text: comment_params[:text])
    if new_comment.save
      flash[:notice] = 'Comment created!'
      redirect_to user_post_path(post.user.id, post.id)
    else
      flash.now[:error] = 'Unable to create comment!'
      redirect_to user_post_path(post.user.id, post.id), alert: 'Failed to add comment!'
    end
  end

  def destroy
    comment = Comment.find params[:id]
    post = comment.post

    if comment.destroy
      redirect_to user_post_path(post.user.id, post.id), notice: 'Comment deleted!'
    else
      redirect_to user_post_path(post.user.id, post.id), alert: 'Failed to delete comment!'
    end
  end

  private

  def comment_params
    params.require(:data).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    new_like = Like.create(user_id: current_user.id, post_id: post.id)
    # new_like.update_likes_counter
    if new_like.save
      redirect_to user_posts_path(post.user.id, post.id), notice: 'Liked'
    else
      redirect_to user_posts_path(post.user.id, post.id), alert: 'Not liked!'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: :all_posts

  def index
    @user = User.find params[:user_id]
    @posts = @user.posts.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
    @comments = @post.comments.all
  end

  def new
    @post = Post.new
  end

  def create
    @new_post = current_user.posts.new post_params

    if @new_post.save
      redirect_to user_posts_path(@new_post.user.id), notice: 'Post successfully created!'
    else
      render :new
    end
  end

  def destroy
    post = Post.find params[:id]
    user = post.user

    if post.destroy
      redirect_to user_path(user.id), notice: 'Post deleted!'
    else
      redirect_to user_path(user.id), alert: 'Failed to delete post!'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::SessionsController
  skip_before_action :verify_authenticity_token
  respond_to :json
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :json
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def get_photo(user)
    user.photo.present? ? user.photo : "https://ui-avatars.com/api/?name=#{user.name}&background=random"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>

  </body>
</html>

app/views/posts/_comment_form.html.erb
<div>
  <%= form_with url: post_comments_path(post.id), scope: :data do |form| %>
    <div>
      <%= form.text_area :text, size: "60x10", required: true, placeholder: "Write comment", class: "text_area" %>
    </div>
    <%= form.submit "Comment" %>
  <% end %>
</div>

app/views/posts/_like_form.html.erb
<div>
  <% if post.likes.exists?(user_id: current_user.id) %>
    <p> Post liked! </p>
  <% else %>
    <%= form_with url: post_likes_path(post.id) do |form| %>
      <%= form.submit "Like" %>
    <% end %>
  <% end %>
</div>

app/views/posts/_new_comment.html.erb
<ul>
  <% comments.each do |comment| %>
    <li>
      <span><%= comment.user.name  %>:  </span>
      <span><%= comment.text %> </span>
    </li>
  </ul>
  <%# Delete comment %>
  <% if can? :destroy, comment %>

    <div>
      <%= button_to "Delete", comment_path(comment.id), data: { confirm: 'Are you sure you want to delete this comment?' }, method: :delete %>
    </div>

  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div class = 'user-posts'>
  <div>
    <h3><%= link_to "Post ##{post.id} - #{post.title}" , user_post_path(@user.id, post.id), class: 'link-comments'%></h3> 
    <%# delete %>
    <% if can? :destroy, post %>
      <div>
        <%= button_to "Delete", post_path(post.id), data: { confirm: 'Are you sure you want to delete this post?' }, method: :delete %>
      </div>
    <% end %>  
  </div>
  <div>
    <p><%= post.text %></p>
    <p> <%= render partial: "posts/total_comments", locals: { total_comments: post.comments.size }%>, 
      <%= render partial: "posts/total_likes", locals: { total_likes: post.likes.size } %>
    </p>
  </div>
</div>

app/views/posts/_post_details.html.erb
<div>
    <h3><%= link_to "Post ##{post.id} - #{post.title}" , user_post_path(@user.id, post.id), class: 'link-comments'%></h3> 
  <p><%= post.text %> </p>
  <div>
    <%= render partial: "posts/total_comments", locals: { total_comments: post.comments.size } %>, 
    <%= render partial: "posts/total_likes", locals: { total_likes: post.likes.size } %>
  </div>
</div>

app/views/posts/_total_comments.html.erb
<span>Comments: <%= total_comments %>

app/views/posts/_total_likes.html.erb
<span>Likes: <%= total_likes %> </span>

app/views/posts/index.html.erb
<section class = 'user-section'>
  <div class  = 'user-image'>
    <img src=<%= get_photo(@user) %> alt="User photo" >
  </div>
  <div class = 'user-content'>
    <div>
      <h2><%= @user.name %></h2>
    </div>
    <div>
      <p class = 'post-num'>Number of posts:<%= @user.posts.size %></p>
    </div>
  </div>
</section>

<% @posts.each do |post|%>
  <div class = 'user-posts'>
    
    <%= render partial: "post_details", locals: { post: post } %>
    
    <% if post.comments.size > 0 %>
      <%= render partial: "new_comment", locals: { comments: post.recent_comments } %>
    <% end %>

  </div>
<% end %>

<div class = 'pagination'>
  <button type="submit" >Pagination</button>
</div>

app/views/posts/new.html.erb
<div class = "new-post">
  <%= form_with url: posts_path, model: @post do |form| %>
    <h2>Create a post</h2>
    <div>
      <%= form.text_field :title, class: "input", size: "50x10", required: true, placeholder: "Post title", value: nil %>
    </div>
    <div>
      <%= form.text_area :text, size: "70x30", required: true, placeholder: "Post content", value: nil %>
    </div>
    <div class = "new-btn">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class = 'show-posts'>
  <div class = 'posts-header'>
    <div>
      <h2>Post <%= @post.id %> by <%= @user.name%></h2>
    </div>
    <div>
      <%= render partial: "posts/total_comments", locals: { total_comments: @post.comments.size } %>, 
      <%= render partial: "posts/total_likes", locals: { total_likes: @post.likes.size } %>
    </div>
  </div>
  <%= render partial: "like_form", locals: { post: @post } %>
  <p><%= @post.text %></p>
</div>

<div class = 'comments'>
  <% if @post.comments.size > 0 %>
    <%= render partial: "new_comment", locals: { comments: @post.comments } %>
  <% end %>
</div>

<div class = "new-post">
  <h3> Add a comment </h3>
  <%= render partial: "comment_form", locals: { post: @post } %>
</div>

app/views/users/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

<% @users.each do |user| %>
  <article class = 'user-section'>
    <div class  = 'user-image'>
      <img src=<%= get_photo(user) %> alt="User photo" >
    </div>

    <div class = 'user-content'>
      <div>
        <h2><%= link_to user.name, user_path(user), class: 'user-name'%></h2>
      </div>

      <div>
        <p class = 'post-num'>Number of posts:<%= user.posts.size %></p>
      </div>
    </div>
  </article>
<% end %>

app/views/users/show.html.erb
<%= link_to "Create a new post", new_post_path(@user.id), class: 'see-posts-button' %>

<section class = 'user-section'>
  <div class = 'user-image'>
    <img src=<%= get_photo(@user) %> alt="User photo" >
  </div>
  <div class = 'user-content'>
    <div>
      <h2><%= @user.name %></h2>
    </div>

    <div>
      <p class = 'post-num'>Number of posts:<%= @user.posts.size %></p>
    </div>
  </div>
</section>

<% if @user.bio.present? %>
	<div class = 'user-bio'>
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>
<% end %>

<%= render partial: 'posts/post', collection: @post %> 
<%= link_to "See all post", user_posts_path(@user.id), class: 'see-posts-button' %>